// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC41EEbYkC7cPfCjPk6RdfjPuPgScCfR9o',
    appId: '1:631154611172:web:12b9772cacbbe476342df1',
    messagingSenderId: '631154611172',
    projectId: 'kesehatan-anak-app',
    authDomain: 'kesehatan-anak-app.firebaseapp.com',
    storageBucket: 'kesehatan-anak-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD46RD-SN_Pj899-MgjA11CSXVIxvz6M0c',
    appId: '1:631154611172:android:309c05b6d02ea50e342df1',
    messagingSenderId: '631154611172',
    projectId: 'kesehatan-anak-app',
    storageBucket: 'kesehatan-anak-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU0I-5JgBOOzFRp5D0Fh_Q9fzmM2iJX4w',
    appId: '1:631154611172:ios:95551f953d784f04342df1',
    messagingSenderId: '631154611172',
    projectId: 'kesehatan-anak-app',
    storageBucket: 'kesehatan-anak-app.firebasestorage.app',
    iosBundleId: 'com.example.appPosy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU0I-5JgBOOzFRp5D0Fh_Q9fzmM2iJX4w',
    appId: '1:631154611172:ios:95551f953d784f04342df1',
    messagingSenderId: '631154611172',
    projectId: 'kesehatan-anak-app',
    storageBucket: 'kesehatan-anak-app.firebasestorage.app',
    iosBundleId: 'com.example.appPosy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC41EEbYkC7cPfCjPk6RdfjPuPgScCfR9o',
    appId: '1:631154611172:web:faf9ee19bafa7723342df1',
    messagingSenderId: '631154611172',
    projectId: 'kesehatan-anak-app',
    authDomain: 'kesehatan-anak-app.firebaseapp.com',
    storageBucket: 'kesehatan-anak-app.firebasestorage.app',
  );
}
